- name: add taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_taps }}"

- name: brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_install }}"

- name: brew cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_cask_apps }}"
